# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_als_cp <- function(Factors, coord, qty, number_iterations, lambdas_etc, UpdateThese, DIM) {
    .Call('_dfTensor_sparse_als_cp', PACKAGE = 'dfTensor', Factors, coord, qty, number_iterations, lambdas_etc, UpdateThese, DIM)
}

sparse_als_wt_cp <- function(Factors, coord, qty, wt, number_iterations, lambdas_etc, UpdateThese, DIM) {
    .Call('_dfTensor_sparse_als_wt_cp', PACKAGE = 'dfTensor', Factors, coord, qty, wt, number_iterations, lambdas_etc, UpdateThese, DIM)
}

sparse_plsa_xd <- function(Factors, coord, qty, number_iterations, tolerances, UpdateThese, prior, DIM) {
    .Call('_dfTensor_sparse_plsa_xd', PACKAGE = 'dfTensor', Factors, coord, qty, number_iterations, tolerances, UpdateThese, prior, DIM)
}

ReconstructSparseTensor <- function(Factors, coord, DIM) {
    .Call('_dfTensor_ReconstructSparseTensor', PACKAGE = 'dfTensor', Factors, coord, DIM)
}

Initialize <- function(coord, qty, initialize_type, decomp_type, nlatent, tdims, DIM) {
    .Call('_dfTensor_Initialize', PACKAGE = 'dfTensor', coord, qty, initialize_type, decomp_type, nlatent, tdims, DIM)
}

Mean_polish <- function(dims, coord, qty, numit, abs_tol, rel_tol, stepsize, DIM) {
    .Call('_dfTensor_Mean_polish', PACKAGE = 'dfTensor', dims, coord, qty, numit, abs_tol, rel_tol, stepsize, DIM)
}

Mean_polish_wtd <- function(dims, coord, qty, wt, numit, abs_tol, rel_tol, stepsize, DIM) {
    .Call('_dfTensor_Mean_polish_wtd', PACKAGE = 'dfTensor', dims, coord, qty, wt, numit, abs_tol, rel_tol, stepsize, DIM)
}

poisson_rates <- function(dims, coord, qty, numit, rel_tol, threshold, DIM) {
    .Call('_dfTensor_poisson_rates', PACKAGE = 'dfTensor', dims, coord, qty, numit, rel_tol, threshold, DIM)
}

sort_indices <- function(coord, is_unique) {
    .Call('_dfTensor_sort_indices', PACKAGE = 'dfTensor', coord, is_unique)
}

